- name: Instalar Docker no Host Remoto
  hosts: jhonata_vm_actions
  become: yes
  remote_user: ubuntu

  tasks:
    # - name: Esperar até que a instância esteja pronta
    #   wait_for:
    #     host: "{{ inventory_hostname }}"
    #     port: 22
    #     delay: 30
    #     timeout: 600
    #     state: started
    #   delegate_to: localhost
    #   async: 0
    #   poll: 0
    #   register: instance_ready
    #   until: instance_ready.failed == false

    # - name: Adquirir o bloqueio do dpkg
    #   shell: "flock /var/lib/dpkg/lock-frontend -c 'sleep 0.1'"
    #   async: 0
    #   poll: 0

    - name: Atualizar lista de pacotes
      apt:
        update_cache: yes
      register: apt_atualizado

    - name: Instalar pacotes necessários
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present
      when: apt_atualizado is succeeded

    # - name: Liberar o bloqueio do dpkg
    #   shell: 
    # - name: Liberar o bloqueio do dpkg
    #   shell: "rm -f /var/lib/dpkg/lock-frontend"

    - name: Adicionar chave GPG do Docker
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Adicionar repositório do Docker
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        state: present

    - name: Instalar Docker
      apt:
        name: docker-ce
        state: present

    - name: Garantir que o Docker esteja rodando
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Copiar chave SSH para a instância
      copy:
        src: ~/.ssh/id_rsa
        dest: /home/ubuntu/.ssh/id_rsa
        owner: ubuntu
        group: ubuntu
        mode: '0600'

    - name: Clonar repositório Git
      become: yes
      become_user: ubuntu
      git:
        #repo: 'https://github.com/DevClaudinei/CRUD-Contatos.git'
        repo: 'git@github.com:jhonatasilva1902/teste_cicd_001.git'
        dest: /home/ubuntu/app
        version: main
        accept_hostkey: yes
