---
- name: Instalar Docker no Host Remoto
  hosts: jhonata_vm_actions
  become: yes
  remote_user: ubuntu
  tasks:
    - name: Esperar até que a instância esteja pronta
      wait_for:
        host: "{{ inventory_hostname }}"
        port: 22
        delay: 60
        timeout: 120
        state: started
      delegate_to: localhost

    - name: Copiar chave SSH privada
      ansible.builtin.copy:
        content: ~/.ssh/id_rsa
        dest: ~/.ssh/id_rsa
        mode: '0600'

    - name: Copiar chave SSH pública
      ansible.builtin.copy:
        content: ~/.ssh/id_rsa.pub
        dest: ~/.ssh/id_rsa.pub
        mode: '0644'

    - name: Atualizar lista de pacotes
      apt:
        update_cache: yes

    - name: Instalar pacotes necessários
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present

    - name: Adicionar chave GPG do Docker
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Adicionar repositório do Docker
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        state: present

    - name: Instalar Docker
      apt:
        name: docker-ce
        state: present

    - name: Garantir que o Docker esteja rodando
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Verificar se a chave SSH existe
      stat:
        path: /home/ubuntu/.ssh/id_rsa  # Caminho para a chave SSH na instância
      register: ssh_key_check

    - name: Exibir resultado da verificação
      debug:
        var: ssh_key_check.stat.exists

    - name: Clonar repositório Git
      become: yes
      become_user: ubuntu
      git:
        repo: 'git@github.com:jhonatasilva1902/teste_cicd_001.git'
        dest: /home/ubuntu/app
        version: main
        accept_hostkey: yes
