---
- name: Instalar Docker no Host Remoto
  hosts: jhonata_vm_actions
  become: yes
  tasks:
    - name: Esperar até que a instância esteja pronta
      wait_for:
        host: "{{ inventory_hostname }}"
        port: 22
        delay: 60
        timeout: 600
        state: started
      delegate_to: localhost

    - name: Atualizar lista de pacotes
      apt:
        update_cache: yes

    - name: Instalar pacotes necessários
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present

    - name: Adicionar chave GPG do Docker
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Adicionar repositório do Docker
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        state: present

    - name: Instalar Docker
      apt:
        name: docker-ce
        state: present

    - name: Garantir que o Docker esteja rodando
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Copiar chave SSH para a instância
      ansible.builtin.copy:
        content: "{{ secrets.SSH_PRIVATE_KEY }}"  # Obtém a chave SSH privada do GitHub Secrets
        dest: /home/ubuntu/.ssh/id_rsa
        owner: ubuntu
        group: ubuntu
        mode: '0600'
      register: copy_result

    - name: Verificar se a cópia da chave SSH foi bem-sucedida
      fail:
        msg: "Falha ao copiar a chave SSH para a instância"
      when: copy_result.failed

    - name: Clonar repositório Git
      become: yes
      become_user: ubuntu
      git:
        repo: 'git@github.com:jhonatasilva1902/teste_cicd_001.git'
        dest: /home/ubuntu/app
        version: main
        accept_hostkey: yes
