name: Excluir Instância AWS

on:
  workflow_dispatch:  # Isso desencadeará o fluxo de trabalho manualmente

jobs:
  delete-instance:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código-fonte
      uses: actions/checkout@v2

    - name: Configurar AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1  # Substitua pela região AWS desejada

    - name: Excluir instância AWS
      run: |
        INSTANCE_NAME=jhonata_vm_actions

        # Obter a ID da instância com base no nome
        INSTANCE_ID=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=$INSTANCE_NAME" --query "Reservations[0].Instances[0].InstanceId" --output text)

        if [ -n "$INSTANCE_ID" ]; then
          aws ec2 terminate-instances --instance-ids $INSTANCE_ID
          echo "Instância $INSTANCE_NAME está sendo excluída."
        else
          echo "Instância $INSTANCE_NAME não encontrada."
        fi

    - name: Excluir Key Pair
      run: |
        KEY_NAME=keypair_jhonata_actions

        # Excluir o key pair
        aws ec2 delete-key-pair --key-name $KEY_NAME
        echo "Key pair $KEY_NAME foi excluído."

    - name: Excluir Security Group
      run: |
        SECURITY_GROUP_NAME=security_group_jhonata_actions

        # Excluir o security group
        aws ec2 delete-security-group --group-name $SECURITY_GROUP_NAME
        echo "Security group $SECURITY_GROUP_NAME foi excluído."
